### ISSUE TITLE
Generelle SARI-Daten?

### ISSUE THREAD

**Issue by jbracher** [robert-koch-institut/COVID-SARI-Hospitalisierungsinzidenz#1]
Guten Tag,

ich bin heute auf dieses Repo gestoßen und freue mich sehr, dass diese Daten in maschinenlesbarer Form verfügbar gemacht werden. Vielen Dank!

Ich hätte auch großes Interesse an den generellen SARI-Daten, wie sie z.B. [hier](https://influenza.rki.de/Wochenberichte/2022_2023/2022-43.pdf) in Abbildung 6 gezeigt werden. Am interessantesten wäre es dabei, auch die Daten pro Altersgruppe zu erhalten. Bestünde diese Möglichkeit?

Beste Grüße, Johannes Bracher

**Comment by jbracher** [comment]
Guten Tag @HannesWuensche, ich wollte mich noch einmal erkundigen, ob Sie hierzu etwas sagen können. Ggf auch gerne per Email (johannes.bracher@kit.edu). Vielen Dank!

**Comment by HannesWuensche** [comment]
Hallo @jbracher ,

bitte entschuldigen sie die verzögerte Rückmeldung. Ich leite ihre Anfrage an die zuständigen Kolleg:innen weiter. 

Mit Besten Grüßen
@HannesWuensche 
für das Team RKI | Open Data

**Comment by jbracher** [comment]
Vielen Dank. Ich wollte gemeinsam mit Kollegen ohnehin bezüglich dieser Daten das RKI / die Arbeitsgemeinschaft Influenza kontaktieren. Wir werden das voraussichtlich nächste Woche machen und kurz erläutern, wieso wir die Daten gern nutzen würden.
