### ISSUE TITLE
Metadaten werden nicht mehr aktualisiert

### ISSUE THREAD

**Issue by marcelpauly** [robert-koch-institut/COVID-SARI-Hospitalisierungsinzidenz#4]
Das Verzeichnis Metadaten ist auf dem Stand von vor einem Monat stehen geblieben.

**Comment by HannesWuensche** [comment]
Hallo @marcelpauly,

vielen Dank für den Hinweis. 
Durch die anhaltenden Probleme mit der neuen Zenodo API haben wir ein paar Umstellungen vornehmen müssen, die hier zu einem Fehler geführt haben.  
Die Metadaten sind  soeben mit den Daten aktualisiert worden. 

Mit besten Grüßen
@HannesWuensche 
für das Team RKI | Open Data
